---
title: "LDA model building"
author: "Jiayi Cui, jc4884"
date: "November 23, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(topicmodels)
```

# data processing
```{r}
# read in non-error documents and form a corpus
path <- "../output/delete_error/"
file_names <- dir(path)
dir_names <- paste(path, file_names, sep = '')
test_ind <- rep(1:20) * 5
test_set <- dir_names[test_ind]
train_set <- dir_names[-test_ind]
corpus <- vector('list', length = length(train_set))
for (i in 1:length(train_set)){
  file <- readLines(train_set[i])
  corpus[[i]] <- file
  writeLines(file, sub("delete_error", "train_set", train_set[i]))
}
for (i in 1:length(test_set)){
  file <- readLines(test_set[i])
  writeLines(file, sub('delete_error', 'test_set', test_set[i]))
}
save(corpus, file = '../output/corpus.RData')
```


```{r}
# Replace word with word id
vocab <- unique(unlist(corpus))
corpus_wordid <- corpus
for (i in 1:length(corpus)){
  corpus_wordid[[i]] <- match(corpus[[i]], vocab)
}
save(corpus_wordid, file = '../output/corpus_wordid.RData')
```


```{r}
# Generate document-term matrix
doc_term <- matrix(0, length(corpus), length(vocab))
for (i in 1:length(corpus)){
  doc_term[i,] <- match(vocab, corpus[[i]])
}
doc_term[is.na(doc_term)] <- 0
save(doc_term, file = '../output/document_term_matrix.RData')
```

# Train LDA model and generate test set probability
```{r}
lda_topic <- LDA(doc_term, 30)
test_corpus <- vector('list', length = length(test_set))
for (i in 1:length(test_set)){
  file <- readLines(test_set[i])
  test_corpus[[i]] <- file
}
save(test_corpus, file = '../output/test_corpus.RData')
test_doc_term <- matrix(0, length(test_corpus), length(vocab))
for (i in 1:length(test_corpus)){
  test_doc_term[i,] <- match(vocab, test_corpus[[i]])
}
test_doc_term[is.na(test_doc_term)] <- 0
save(test_doc_term, file = '../output/test_doc_term_matrix.RData')
lda_inf <- posterior(lda_topic, test_doc_term)
```

```{r}
# test set document-topic probability
lda_inf$topics
```

```{r}
# Generate term-topic probability
lda_inf$terms[,1:10]
```

